#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --time=12:00:00
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user yshi@psu.edu

echo "Job started on `hostname` at `date`"
jobstart=`date +%s`

# Run spin-up
git checkout HEAD input/WE38/WE38.para
git checkout HEAD input/WE38/WE38.lsm
./flux-pihm -bo hydro_spinup WE38

# Copy generated initial condition file to input directory
cp output/hydro_spinup/restart/WE38.*.ic input/WE38/spinup2/WE38.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_1dot25xN/spinup2/WE38_1dot25xN.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_1dot5xN/spinup2/WE38_1dot5xN.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_lowland/spinup2/WE38_lowland.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_lowland_manure/spinup2/WE38_lowland_manure.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_upland/spinup2/WE38_upland.ic
cp output/hydro_spinup/restart/WE38.*.ic input/WE38_upland_manure/spinup2/WE38_upland_manure.ic

jobend=`date +%s`
echo -e "\nJob ended at `date`"
dt=$((jobend - jobstart))
ds=$((dt % 60))
dm=$(((dt / 60) % 60))
dh=$((dt / 3600))
printf "Elapsed time %d:%02d:%02d" $dh $dm $ds
